[package]
name = "raphy"
version = "0.1.2"
authors = ["Brandon Lucia <blucia@gmail.com>"]
edition = "2018"
description = "A rudimentary graph data structure library"
license = "Apache-2.0"
homepage = "https://brandonlucia.com"
repository = "https://github.com/blucia0a/raphy"
documentation = "https://github.com/blucia0a/raphy/blob/master/README"

[dependencies]
rand = "0.7.0"
